# Generated by Django 4.2.6 on 2023-11-03 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_alter_customuser_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[(1, 'Man'), (2, 'Woman'), (3, 'Other'), (4, 'Prefer not to say')], max_length=100),
        ),
    ]
