# Generated by Django 4.2.6 on 2023-11-03 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_alter_customuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('man', 'Man'), ('woman', 'Woman'), ('other', 'Other'), ('nothing', 'Prefer not to say')], max_length=100),
        ),
    ]
